/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_utils_CUtils */

#ifndef _Included_com_utils_CUtils
#define _Included_com_utils_CUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_utils_CUtils
 * Method:    encode
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_utils_CUtils_encode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_utils_CUtils
 * Method:    decode
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_utils_CUtils_decode
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
