/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_point_ffmpegdemo_FFmpegNdk */

#ifndef _Included_com_point_ffmpegdemo_FFmpegNdk
#define _Included_com_point_ffmpegdemo_FFmpegNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_point_ffmpegdemo_FFmpegNdk
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_point_ffmpegdemo_FFmpegNdk_avcodecinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_point_ffmpegdemo_FFmpegNdk
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_point_ffmpegdemo_FFmpegNdk_playVideo
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
